export const dataScheduleDetail = [
  {
    name: "Alice Johnson",
    phone: "+1234567890",
    email: "alice.johnson@example.com",
    start_address: "123 Main St, Da Nang",
    end_address: "789 Oak Ave, Da Nang",
    seat_number: 1,
    status: "Đã Lên Xe",
  },
  {
    name: "Bob Smith",
    phone: "+1987654321",
    email: "bob.smith@example.com",
    start_address: "456 Elm St, Da Nang",
    end_address: "101 Pine Rd, Da Nang",
    seat_number: 2,
    status: "Chưa Lên Xe",
  },
  {
    name: "Carol Williams",
    phone: "+1231231234",
    email: "carol.williams@example.com",
    start_address: "789 Oak St, Da Nang",
    end_address: "202 Cedar St, Da Nang",
    seat_number: 3,
    status: "Đã Xuống Xe",
  },
  {
    name: "David Brown",
    phone: "+3216549870",
    email: "david.brown@example.com",
    start_address:
      "101 Pine Rd, Da Nang ákkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkdhj",
    end_address: "303 Birch Ave, Da Nang",
    seat_number: 4,
    status: "Đã Lên Xe",
  },
  {
    name: "Eve Davis",
    phone: "+1478523690",
    email: "eve.davis@example.com",
    start_address: "202 Cedar St, Da Nang",
    end_address: "404 Maple St, Da Nang",
    seat_number: 5,
    status: "Đã Lên Xe",
  },
  {
    name: "Frank Miller",
    phone: "+1597534860",
    email: "frank.miller@example.com",
    start_address: "303 Birch Ave, Da Nang",
    end_address: "505 Walnut Rd, Da Nang",
    seat_number: 6,
    status: "Chưa Lên Xe",
  },
  {
    name: "Grace Wilson",
    phone: "+9513574680",
    email: "grace.wilson@example.com",
    start_address: "404 Maple St, Da Nang",
    end_address: "606 Chestnut Ln, Da Nang",
    seat_number: 7,
    status: "Đã Lên Xe",
  },
  {
    name: "Henry Taylor",
    phone: "+7539512840",
    email: "henry.taylor@example.com",
    start_address: "505 Walnut Rd, Da Nang",
    end_address: "707 Redwood Dr, Da Nang",
    seat_number: 8,
    status: "Đã Lên Xe",
  },
  {
    name: "Isla Martin",
    phone: "+8529637410",
    email: "isla.martin@example.com",
    start_address: "606 Chestnut Ln, Da Nang",
    end_address: "808 Cypress St, Da Nang",
    seat_number: 9,
    status: "Đã Lên Xe",
  },
  {
    name: "Jack White",
    phone: "+9517538246",
    email: "jack.white@example.com",
    start_address: "707 Redwood Dr, Da Nang",
    end_address: "909 Palm St, Da Nang",
    seat_number: 10,
    status: "Đã Lên Xe",
  },
];
